""" Created on Mon Nov  6 10:29:44 2023
    @author: dcupolillo """

from pathlib import Path
import numpy as np
import tifffile
from ROIpy.core.components import Node


def parse_stack_metadata(
        image_name: str or Path
) -> dict:

    with tifffile.TiffFile(image_name) as tif:
        scanimage_metadata = tif.scanimage_metadata

    framedata = scanimage_metadata['FrameData']
    roigroups = scanimage_metadata['RoiGroups']

    stack_name = framedata['SI.hScan2D.logFileStem']
    data_type = framedata['SI.hScan2D.channelsDataType']
    corners_um = framedata['SI.hRoiManager.imagingFovUm']
    corners_deg = framedata['SI.hRoiManager.imagingFovDeg']
    width_pix = framedata['SI.hRoiManager.pixelsPerLine']
    height_pix = framedata['SI.hRoiManager.linesPerFrame']
    
    width_um = np.abs(
        min(corners_um[0])
        - max(corners_um[1]))
    height_um = np.abs(
        min(corners_um[2])
        + max(corners_um[3]))
    width_deg = np.abs(
        min(corners_deg[0])
        - max(corners_deg[1]))
    height_deg = np.abs(
        min(corners_deg[2])
        + max(corners_deg[3]))
    
    pix_um_ratio = width_pix / width_um
    units_um = 'µm'
    units_deg = 'deg'
    zoom = framedata['SI.hRoiManager.scanZoomFactor']
    zs = framedata['SI.hStackManager.zs']

    # To deal with eventual averaging stack planes
    if len(zs) != len(set(zs)):
        zs = list(set(zs))

    z_distance = np.abs(np.diff(zs)[0])
    n_slices = framedata['SI.hStackManager.actualNumSlices']
    stack_start = framedata['SI.hStackManager.stackZStartPos']
    stack_end = framedata['SI.hStackManager.stackZEndPos']

    objective_resolution = framedata['SI.objectiveResolution']

    pixel_to_ref_transform = np.array(
        roigroups['imagingRoiGroup']['rois']
                 ['scanfields']['pixelToRefTransform'])
    affine = np.array(
        roigroups['imagingRoiGroup']['rois']
                 ['scanfields']['affine'])

    n_channel_available = (
        framedata['SI.hChannels.channelsAvailable'])
    ch_available_list = np.arange(n_channel_available)
    ch_active = (
        [framedata['SI.hChannels.channelsActive']]
        if isinstance(
        framedata['SI.hChannels.channelsActive'], int)
        else framedata['SI.hChannels.channelsActive'])

    ch_active_list = [
        True if (ch + 1) in ch_active else False
        for ch in ch_available_list]

    n_channels = (
        1 if isinstance(ch_active, int)
        else len(ch_active))

    return {
        'stack_name': stack_name,
        'data_type': data_type,
        'corners_um': corners_um,
        'corners_deg': corners_deg,
        'width_pix': width_pix,
        'height_pix': height_pix,
        'width_um': width_um,
        'height_um': height_um,
        'width_deg': width_deg,
        'height_deg': height_deg,
        'pix_um_ratio': pix_um_ratio,
        'units_um': units_um,
        'units_deg': units_deg,
        'zoom': zoom,
        'zs': zs,
        'z_distance': z_distance,
        'n_slices': n_slices,
        'stack_start': stack_start,
        'stack_end': stack_end,
        'objective_resolution': objective_resolution,
        'pixel_to_ref_transform': pixel_to_ref_transform,
        'affine': affine,
        'n_channel_available': n_channel_available,
        'ch_available_list': ch_available_list,
        'ch_active': ch_active,
        'ch_active_list': ch_active_list,
        'n_channels': n_channels
    }


def parse_swc(
        filename: str,
        objective_resolution: float,
        zs: list,
        pixel_to_ref_transform: list or np.ndarray
) -> list:
    """
    Parse an SWC file and generate a list of Node instances.
    Only tested for .swc files generated by SNT plugin in ImageJ.

    Parameters
    ----------
    filename : str
        Path to the SWC file containing the neuronal morphology data.
    objective_resolution : float
        Resolution of the objective used, stored in the image metadata.
    zs : list
        List of Z slice positions in micrometers (µm).
    pixel_to_ref_transform : list or np.ndarray
        Transformation matrix for converting pixel coordinates to
        reference space.

    Returns
    -------
    list
        List of Node instances representing the parsed morphology.
    """

    nodes = []
    x_voxel_separation, y_voxel_separation = None, None

    with open(filename, 'r') as f:

        for n_line, line in enumerate(f):
            if line.startswith('#'):
                if n_line == 4:
                    header_fields = line.strip().split()
                    x_voxel_separation = float(header_fields[4][:-1])
                    y_voxel_separation = float(header_fields[5][:-1])
                continue  # skip comment lines

            fields = line.strip().split()

            # Create individual Node instances
            node = Node(
                obj_res=objective_resolution,
                _id=fields[0],
                _type=fields[1],
                x=fields[2],
                y=fields[3],
                z_ind=fields[4],
                zs=zs,
                radius=fields[5],
                parent_id=fields[6],
                matrix=pixel_to_ref_transform,
                voxel_separation_x=x_voxel_separation,
                voxel_separation_y=y_voxel_separation)
            nodes.append(node)

    # Compute parent node
    for node in nodes:
        parent_id = node.parent_id
        if parent_id != -1:  # Skip root node
            parent_node = next(n for n in nodes if n._id == parent_id)
            parent_node.children.append(node.id)

    # Update is_fork attribute for each node based on children count
    for node in nodes:
        node.is_fork = len(node.children) > 1

    return nodes


def is_new_branch(
        node: object,
        previous_node: object
) -> bool:
        
        return (
            node.parent_id != previous_node.id or
            node.parent_id is None)


def assign_branch_degree_and_id(input_data):
    """
    Assign branch degrees and unique branch IDs to nodes
    in the neuronal morphology.

    Parameters
    ----------
    input_data : NodeBundle
        Morphology structure containing nodes.

    Returns
    -------
    NodeBundle
        The input NodeBundle with updated `branch_degree` and `branch_id`.

    Updates
    -------
    - Each node's `branch_degree` is updated to reflect its hierarchical level.
    - Each node's `branch_id` is updated to uniquely identify its neurite.
    """
    branch_id_counter = 0
    soma_node_id = input_data[0].id
    already_classified_nodes = set()

    branch_degree = 1
    current_branch_nodes = []

    for node in input_data:
        if node._type == "soma":
            # Assign branch ID and degree for the current section
            if current_branch_nodes:
                for branch_node in current_branch_nodes:
                    branch_node.branch_id = branch_id_counter
                    branch_node.branch_degree = branch_degree
                branch_id_counter += 1
                branch_degree += 1
            current_branch_nodes = []
        else:
            # Add node to the current branch or start a new one
            if not current_branch_nodes or is_new_branch(node, current_branch_nodes[-1]):
                if current_branch_nodes:
                    for branch_node in current_branch_nodes:
                        branch_node.branch_id = branch_id_counter
                        branch_node.branch_degree = branch_degree
                    branch_id_counter += 1
                current_branch_nodes = [node]
            else:
                current_branch_nodes.append(node)

    # Assign IDs for the last branch
    if current_branch_nodes:
        for branch_node in current_branch_nodes:
            branch_node.branch_id = branch_id_counter
            branch_node.branch_degree = branch_degree

    return input_data

